name: Firebase App Distribution

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch:
    inputs:
      release_notes:
        type: string
        required: true
        default: 'Manual Debug Build'
        description: 'Release Notes'

jobs:
  upload-to-firebase:
    name: Upload APK to Firebase App Distribution
    runs-on: ubuntu-latest

    steps:
      # Checkout your repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Java JDK (with Zulu distribution)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'  # Specifies the JDK distribution (can be zulu, adopt, temurin, etc.)
          java-version: '11'

      # Cache Gradle dependencies for faster builds
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # Clean Build
      - name: Clean Build Folder
        run: cd android && ./gradlew clean

      # Build the APK
      - name: Build APK
        run: cd android && ./gradlew assembleRelease

      # Upload the APK to Firebase App Distribution
      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: android/app/build/outputs/apk/release/app-release.apk  # Adjusted path to the release APK
          releaseNotes: ${{ github.event.inputs.release_notes }}  # Use the provided release notes